name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: |
          [ -n "$NODE_AUTH_TOKEN" ] && npm config set //registry.npmjs.org/:_authToken "$NODE_AUTH_TOKEN"
          npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
